### ISSUE TITLE
Set data-concept-id appropriately for inputs, fieldsets, selects, options, and textareas

### ISSUE THREAD

**Issue by kml27** [esaude/mental-health#10]
based on the matching concepts from the downloaded concept dictionary...

e.g.

```                    
<select data-concept-id="23772" name="symptom-assessment-gravity" id="symptom-assessment-gravity">
    <option data-concept-id="23773" value="light"> 1 - Light </option>
    <option data-concept-id="1384" value="moderate"> 2 - Moderate </option>
    <option data-concept-id="23774" value="serious"> 3 - Serious </option>
    <option data-concept-id="23775" value="deep"> 4 - Deep </option>
</select>
```

**Comment by kml27** [comment]
We should add key,value pairs to the message.properties and use those strings in place of the plaintext in the options in this example.

**Comment by jsibley** [comment]
Nicholas has already given us a good starting point for the properties files.  I'll be expanding on what he's given us this weekend.  Thanks Nicholas!

**Comment by jsibley** [comment]
This is probably 90-95% done.

**Comment by jsibley** [comment]
The ones that I know of that still need concepts:
Depressive Disorder on initial form, section 7
Absence Epilepsy on initial form, section 7
Need to relabel Schizophrenic Disorder as Schizophreniform Disorder on initial form, section 7

**Comment by jsibley** [comment]
Should be all set now.
