### ISSUE TITLE
postSubmissionAction enrollment

### ISSUE THREAD

**Issue by kml27** [esaude/mental-health#18]
Add postSubmissionAction for Initial Intake form to enroll patient in MH program

Pros:
 - avoids mixing server side commands into html

Can probably use the same obj.method() as that used in HFE program enrollment/progression tags.

**Comment by kml27** [comment]
Check for program enrollment before enrolling. Handle lost to followup and re-enrollment conditions, exit and re-enroll if necessary.

**Comment by jsibley** [comment]
High priority.  Probably dependent on getting the program states defined.

**Comment by jsibley** [comment]
Shouldn't need any workflow states defined to implement this.
program_id = 10
Just set date_enrolled to the date when initial form was submitted.

**Comment by jsibley** [comment]
Auto enrollment on initial form submission is complete
