### ISSUE TITLE
allow elements to use lookup expressions

### ISSUE THREAD

**Issue by kml27** [esaude/mental-health#19]
attr data-lookup-expression="" should use same method as <lookup expression=""> (velocity fn in FormEntrySession) and set an element's value="" attr.

**Comment by jsibley** [comment]
What's the use case for this one?

**Comment by kml27** [comment]
html5 compliance, since there's a lack of HFE schema for xml validators (not strictly needed, but simple to impl., already in the batch of features)

**Comment by kml27** [comment]
data-lookup-expression-value="true" and value="velocity.expression"
