### ISSUE TITLE
Some inputs not showing previously entered values when viewing a saved form

### ISSUE THREAD

**Issue by jsibley** [esaude/mental-health#26]
Data is being saved in 'obs' table (for the most part), but the following fields (and maybe more) don't get the values back when displayed.

'If yes, specify' text boxes in Family History section
Some (perhaps all) text boxes in Patient History section
All text boxes in Symptom Assessment section (seems to be all "type=number" fields)
Checkboxes in Mental Health Disorders section

**Comment by kml27** [comment]
created new issue #31 for All text boxes in Symptom Assessment section (seems to be all "type=number" fields)

**Comment by kml27** [comment]
cannot replicate, 'If yes, specify' text boxes in Family History section, may be related to https://github.com/kml27/mental-health-mockup/blob/0bb33ffc05e806e894400582210f57963b3765c4/js/common.js#L410, correct fix for #25 in https://github.com/kml27/mental-health-mockup/commit/c5892628ba8c5cf8b50492f8c589015f400184c4, and removal of early return when control.disabled in https://github.com/kml27/mental-health-mockup/blob/17ea793ff8449e9f46a1b1f0bced5ffa3cf4214a/js/common.js#L418 for #38

**Comment by kml27** [comment]
cannot replicate, Some (perhaps all) text boxes in Patient History section, reference those changes in previous comment for reason(s)

**Comment by jsibley** [comment]
Works now.
