### ISSUE TITLE
after login times out, submit on form (edit) doesnt ask for login credentials

### ISSUE THREAD

**Issue by kml27** [esaude/mental-health#28]
at least on form edit, may just need to have onsubmit set to "submitHtmlForm();"

**Comment by kml27** [comment]
setting /usr/local/tomcat/conf/web.xml
<session-timeout>30</session-timeout> seemed to work to shorten the timeout for testing

**Comment by kml27** [comment]
a yellow popup should popup if the session timed out to supply credentials

add onclick="submitHtmlForm()" attribute to input type="submit" here in initial.xml
https://github.com/esaude/mental-health/blob/f1a9d2f2eea40f884ef41f8e8201273219662cdb/omod/src/main/webapp/resources/htmlforms/initial.xml#L1088

and replace this line with the same submit input in follow_up.xml
https://github.com/esaude/mental-health/blob/f1a9d2f2eea40f884ef41f8e8201273219662cdb/omod/src/main/webapp/resources/htmlforms/follow_up.xml#L698

**Comment by kml27** [comment]
I believe it starts counting since last server request (i.e. clicking edit link)...

![image](https://user-images.githubusercontent.com/12536853/45725167-5a43f580-bb6e-11e8-8ac3-5a7d5447aebf.png)

**Comment by jsibley** [comment]
Working now.
