### ISSUE TITLE
on submission failure, sec 7, drug use other drug, specify other drug field is disabled and blank

### ISSUE THREAD

**Issue by kml27** [esaude/mental-health#34]
observed:
input disabled and blank

expected:
input enabled and contains same text as was present before submission

probably related to https://github.com/kml27/mental-health-mockup/blob/05c3f1822a3c9385b47f518d515c97c2fed98a67/js/common.js#L443-L449

select intial intake form
select tab for section 7
check drug use
select other drug use
enter value for other drug use text input
submit form (without having selected encounter date, location, or provider)

**Comment by kml27** [comment]
fix in commits:
https://github.com/kml27/mental-health-mockup/commit/a407107aabd1683f616cb2032043367a99ebe87b
through
https://github.com/kml27/mental-health-mockup/commit/0387da71423b28683aa8956907c174423998cc35

**Comment by kml27** [comment]
dependent on #37

**Comment by jsibley** [comment]
Working now.
