### ISSUE TITLE
Concepts for diagnoses on followup form not being found in database?

### ISSUE THREAD

**Issue by jsibley** [esaude/mental-health#39]
Exception! Concept for select #primary-dx-list form name primary-dx-list and value caf7ac69-a874-445d-b738-2556b45faf64 not found!<br/>java.lang.IllegalArgumentException: Concept for select #primary-dx-list form name primary-dx-list and value caf7ac69-a874-445d-b738-2556b45faf64 not found! at org.openmrs.module.mentalhealth.elements.SelectElement.handleSubmission(SelectElement.java:71) at org.openmrs.module.htmlformentry.FormSubmissionController.handleFormSubmission(FormSubmissionController.java:128) at

**Comment by kml27** [comment]
Steps to replicate this issue: 
Select an option from the diagnosis or diagnosis secondary drop downs. Fill in encounter date, provider and location and submit.

**Comment by ccwhite333** [comment]
diagnosis and secondary diagnosis are not available for selection on my screen. 
<img width="1245" alt="screen shot 2018-09-19 at 6 15 20 pm" src="https://user-images.githubusercontent.com/15679308/45790091-03a2ee00-bc38-11e8-8675-4cc2a0e36b4a.png">

**Comment by kml27** [comment]
the xml on openmrs-mhrp hasnt been updated yet

**Comment by kml27** [comment]
The xml has been updated. This can be tested.

**Comment by jsibley** [comment]
Think this is working now.
