### ISSUE TITLE
Need JS function to choose correct FNM select option from hidden name and form fields on page load.

### ISSUE THREAD

**Issue by jsibley** [esaude/mental-health#40]

**Comment by kml27** [comment]
allows negative quantities (number input has no min) 
![image](https://user-images.githubusercontent.com/12536853/45786879-6b9d0880-bc27-11e8-9668-94dc55ac9451.png)

**Comment by jsibley** [comment]
Fix pushed to Github, will require rebuild of module (or manual XML change).
