### ISSUE TITLE
two default checked radios exist in edit mode when a radio besides "not provided" is checked

### ISSUE THREAD

**Issue by kml27** [esaude/mental-health#49]
a symptom of this is cleared dependent disabled state inputs on pages like initial intake - family history(sec 3), patient history(sec 4), and mental health (sec 7) i.e. please specify fields

**Comment by kml27** [comment]
@jsibley this may be a symptom you were seeing and mentioning in other cases. I think I was still seeing older xml templates until yesterday ( https://github.com/esaude/mental-health/commit/d5ffbcaca370d982bc8833e5954560977276036f )?.

**Comment by kml27** [comment]
In enter mode, select the yes radio that enables "if yes, please specify". Enter a value in the text input. Set the encounter date, location and provider. Save the form. View the form. Verify the correct value shows up in that text input. Click Edit link. Check whether that text input has a value or is blank. Text input should still have the entered value.

**Comment by ccwhite333** [comment]
This works for all text inputs except other drugs on tab 7

**Comment by kml27** [comment]
the observed issue is new. The symptom is the same. Created new issue #52
