### ISSUE TITLE
initial form - unchecking a checkbox on sec 7 in edit mode does not void it on submission

### ISSUE THREAD

**Issue by kml27** [esaude/mental-health#50]
Observed:
The checkbox remains checked on subsequent views of the form.

Expected:
The checkbox is in whatever state was selected when the edit form is submitted.

Steps:
Create a form with a checkbox checked on section 7.
Select encounter values.
Save.
View Form.
Edit Form.
Uncheck checkbox.
Save.
View Form.
See the checkbox is still checked.

**Comment by ccwhite333** [comment]
still happening on tin

**Comment by kml27** [comment]
yes, that's the message at 2:55 that the fix was pushed, and @jsibley saying he hadn't installed the new build at 3:04 yet, and to let him know when a good time for him to do so is.

**Comment by jsibley** [comment]
Working now.
