### ISSUE TITLE
Follow Up Form - Saving after edit clears Medications

### ISSUE THREAD

**Issue by kml27** [esaude/mental-health#53]
Create a follow up form selecting medications from selects.
Set encounter details.
save.
view.
edit.
(might not even need to...) ?change medication?
view.
blank medication fields.

**Comment by jsibley** [comment]
Just pushed a JS fix that should repair this.

**Comment by kml27** [comment]
https://github.com/kml27/mental-health-mockup/commit/deed640492ce779e3f597a0fb92b2b614583b1ad

**Comment by jsibley** [comment]
Pushed real fix now.
