### ISSUE TITLE
Values should be url encoded before storing in database

### ISSUE THREAD

**Issue by kml27** [esaude/mental-health#6]
textarea in view mode for example should not be interpreted as innerHtml (i.e. use textContent rather than innerHtml). Submitted obs values should be url encoded to prevent xss.

**Comment by jsibley** [comment]
This isn't working right.  It's storing the URL encoded strings in the database, which then are shown on in the existing form view.  For example, if I enter a string "Text with spaces", and then I re-load the form, it shows up as 'Text+with+spaces".  I don't think we want to be storing encoded values in the database.

**Comment by kml27** [comment]
changing escapes to use org.apache.commons.lang.StringEscapeUtils

**Comment by jsibley** [comment]
Working better now, though any `&` characters come back as `&amp;` in text fields.

**Comment by jsibley** [comment]
I think this is fixed, closing.
