### ISSUE TITLE
Option and Label should use OpenMRS message.properties mechanism

### ISSUE THREAD

**Issue by kml27** [esaude/mental-health#7]
setting label or option data-translate="true" will use

Context.getMessageSourceService().getMessage(translationPair.getKey());

to replace the key in message_(lang).properties with the matching string

**Comment by kml27** [comment]
translate is now enabled by default for labels and options, data-translate="false" (or anything other than "true") will disable it

**Comment by jsibley** [comment]
Is this only available for <label> and <option> tags?  Or can I use it for the <title> tag too?
