### ISSUE TITLE
Update labels and options to use message.properties keys

### ISSUE THREAD

**Issue by kml27** [esaude/mental-health#9]
Now that labels and options translate by default, labels should be updated to the key rather than the value for a given language. If time permits, I can add the properties files to the mockup and have js do a simple replace (nothing fancy), to aid in quick turn around for any cosmetic changes.

NOTE: tabs and spaces inside the label tag are not currently trimmed. e.g. "mentalhealth.form.initial.title\t" is not translated.

**Comment by jsibley** [comment]
No need to do anything fancy (or non-fancy) to autogenerate the keys.  Since I need to touch every input to add the concept anyway, I'll be replacing the text with keys at the same time.  Thanks!

**Comment by jsibley** [comment]
This is probably 95-99% complete.

**Comment by jsibley** [comment]
Double-checked all of these tonight... looks good!
